### ISSUE TITLE
When play CS:GO the program crashed

### ISSUE THREAD

**Issue by M0rkzen** [G-Stas/Volumey#58]
Hello there,
I just installed the program, everything work fine but when i play cs the program just no respond then crash

**Comment by Drakime** [comment]
I was having the same issue - the program would crash whenever I launched a game.

For now, it seems to be working when running the program with administrator privileges.

Edit: Turns out, the issue still occurs.

**Comment by G-Stas** [comment]
Will try to reproduce.
For now, do you have any Volumey.exe.dmp crashdumps under the {systemdrive}:\Users{user}\AppData\Local\CrashDumps? If so, could you please upload it somewhere so I could check it? It shouldn't contain any private data.

**Comment by Drakime** [comment]
Here's a link to the crashdump file:

https://file.io/UCihCzxXJ4jz

**Comment by G-Stas** [comment]
Can't reproduce and not much info in the dump, unfortunately. 
Could you open Event Viewer in Windows, go to Windows logs → Application, click 'Filter current log' on the right side, set parameters like on the screenshot, click OK, then click 'Find' and search by Volumey. If there are any logs found, please copy content of the General tab here. 
![mmc_2nO9AER0WH](https://github.com/G-Stas/Volumey/assets/35915435/16be05bd-31a5-4071-bae0-ed53796d224a)

**Comment by Drakime** [comment]
Here you go:

Application: Volumey.exe
CoreCLR Version: 4.700.22.55902
.NET Core Version: 3.1.32
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (1816): Not enough quota is available to process this command.
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by M0rkzen** [comment]
Any news?

**Comment by ComanderKen** [comment]
Hi, I probably have the same isue.
When I play games with GeForce Now for longer periods of time, the program crashes. 

Any news?
